[project]
name = "scarlet-locomotive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "scarlet-locomotive", email = "scarletlocomotive@proton.me" }
]
requires-python = ">=3.12"
dependencies = []

[tool.maturin]
module-name = "scarlet_locomotive._core"
python-packages = ["scarlet_locomotive"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
